# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies & gcc
      run: |
        python -m pip install --upgrade pip
        sudo apt install build-essential
        ls
    - name: Download Coverity Build Tool
      run: |
          wget https://scan.coverity.com/download/linux64 --post-data "token=b3lk_nYKE3JXiV6Nv6qs8A&project=adithya1995%2Ftictactoe" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
    - name: Fixed world writable dirs
      run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
    - name: Configure
      run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-configure --compiler /usr/bin/gcc --comptype gcc
    - name: Build with cov-build
      run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir coverity gcc hello.cpp 
    - name: Analyze with Coverity
      run: |
          tar czvf cov.tgz coverity
          curl \
          --form token=b3lk_nYKE3JXiV6Nv6qs8A \
          --form email=adithya95dk@gmail.com \
          --form file=@cov.tgz \
          --form version="1.0" \
          --form description="Description" \
          https://scan.coverity.com/builds?project=adithya1995%2Ftictactoe
    - name: Test with unittest module
      run: |
        python testcalc.py
